# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3d020e718a8a9bdf822f4003e7fb9e24c73e5601b9e1413b93d0dbf6b5af485a01a9cd9345ea85f68f0ec55dbadd2f613ef27c5ea435908687ab85ab86985e

test:
  secret_key_base: 387c6311b68d2ba8b7d87c0ca4672def7554ee5f3a607ce7129852cf18b69f9950ac01c04ab9cc8c73838abc1933573f584a8aba56bb0acf3b3455263c769a4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
